apiVersion: v1
kind: Service
metadata:
  name: itsm-app
  labels:
    app.kubernetes.io/name: itsm-app
    app.kubernetes.io/component: itsm
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: itsm-app
  ports:
    - name: http
      port: 8000
      targetPort: http
