apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: gen-ai-k8s-playground-agent
    newName: quay.io/calopezb/gen-ai-k8s-playground-agent
    newTag: latest
  - name: gen-ai-k8s-playground-chat
    newName: quay.io/calopezb/gen-ai-k8s-playground-chat
    newTag: latest
  - name: gen-ai-k8s-playground-tools
    newName: quay.io/calopezb/gen-ai-k8s-playground-tools
    newTag: latest
