apiVersion: v1
kind: Service
metadata:
  name: monitor
  labels:
    app.kubernetes.io/name: monitor
    app.kubernetes.io/component: monitor
spec:
  selector:
    app.kubernetes.io/name: monitor
  ports:
    - name: http
      port: 9010
      targetPort: http
