apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gen-ai-playground

resources:
  - namespace.yaml
  - agent
  - chat

commonLabels:
  app.kubernetes.io/part-of: gen-ai-playground
  demo: gen-ai-k8s-playground
