FROM registry.access.redhat.com/ubi9/python-311:latest

WORKDIR /app

COPY requirements.txt main.py .
COPY static static
COPY templates templates

USER 0
RUN pip install --no-cache-dir -r requirements.txt && \
    chown -R 1001:0 /app && \
    chmod -R g=u /app

ENV PORT=5000 \
    AGENT_URL=http://localhost:8080 \
    AGENT_TIMEOUT=120
EXPOSE 5000

USER 1001

CMD ["python", "main.py"]
